#!/bin/sh
status=$(wpctl get-volume @DEFAULT_AUDIO_SINK@)

if (echo $status | grep -q '[MUTED]'); then
  echo " "
else
   vol=$(echo $status | cut -d' ' -f2)
   printf " %d%%" $(echo "100 * $vol" | bc)
fi
