# options
set -g base-index 1
set -g renumber-windows on

# keybinds
set -g prefix C-Space
set -g mode-keys vi
bind-key -r f run-shell "tmux neww ~/.local/bin/tmux-sessionizer"
bind l next-window
bind h previous-window

# status bar
set -g status-position top
set -g status-interval 5
set -g status-left-length 20
set -g status-style "bg=default"
set -g window-status-format "#W"
set -g window-status-current-format "#[bold]#W"
